print("this is for testing only")
print("combine 1")
print("combine 2")
print("combine 3")
print("combine 4")
print("combine 4")
print("this is the bug test 1")
print("thi is the bug test 2")
print("this is the actual bug")
print("thi is the bug test 3")
print("this is the mohan")
print("this is for only merge")
print("this is the merge from master to dev")
print('this is for only testing')
print("this is only testing")
print('this is the new merge1')
print("this is the new merge2")
print("this is the new merge3")
print('fast forward1')
print("fast forward2")
print("master to dev three way1")
print("master to dev three way2")
print("checking merge commit1")
print('rebase change')
print('rebase dev to maaster')
print('rebase masater to dev')
print("rebase m to d 1")
print("rebase d to m 1")
print("rebase d to m 2")
print("rebase m to d 2")
print("rebase m to d 3")
print("rebase master to dev final")
print("rebase master to dev final1")
